### ISSUE TITLE
stylelint: transparent 应该放在白名单，不强制要求单独为它声明一个变量

### ISSUE THREAD

**Issue by Aokoooooo** [MiaoSiLa/dotfiles#9]
![image](https://user-images.githubusercontent.com/32900608/128388226-0d2a79a6-dbe5-473c-b449-bdb50429e418.png)
这个值没必要单独创建变量，应该在 [declaration-property-value-allowed-list](https://stylelint.io/user-guide/rules/list/declaration-property-value-allowed-list) 配置忽略

**Comment by sweetliquid** [comment]
https://github.com/MiaoSiLa/dotfiles/issues/7

**Comment by sweetliquid** [comment]
之前已经开 ISSUE 了，一直没时间做
